export const products = [
{id:"wraith",name:"Wraith",group:"ai",category:"Security & red team",price:24,description:"14 skills for security and red-team workflows.",detail:"Explore the full skill list and supported workflows before purchasing.",url:"https://buy.stripe.com/cNi5kEaZB12L7QN9C7fnO04",icon:"◇"},
{id:"animus",name:"Animus",group:"ai",category:"AI engineering",price:24,description:"13 skills for building with AI.",detail:"AI engineering skill pack. Read the full description for its contents and how to use them.",url:"https://buy.stripe.com/cNi4gAebN12L1sp7tZfnO06",icon:"⟐"},
{id:"thrall",name:"Thrall",group:"ai",category:"Agent orchestration & memory",price:24,description:"13 skills for agents, orchestration, and memory.",detail:"Agent and automation toolkit. Review the included skills against your agent environment.",url:"https://buy.stripe.com/fZu7sMgjV9zhfjf01xfnO0a",icon:"⊙"},
{id:"siren",name:"Siren",group:"work",category:"SEO & content",price:19,description:"15 skills for content and search workflows.",detail:"SEO and content skill pack. The current product page lists each included skill.",url:"https://buy.stripe.com/cNi6oI0kXdPx4EB6pVfnO01",icon:"◈"},
{id:"reaper",name:"Reaper",group:"work",category:"Sales & leads",price:19,description:"13 skills for sales and lead operations.",detail:"Sales and lead operations skill pack. Review the full contents before purchasing.",url:"https://buy.stripe.com/dRm8wQc3FeTBefbg0vfnO02",icon:"⌁"},
{id:"horde",name:"Horde",group:"work",category:"Business automation",price:19,description:"14 skills for automating business workflows.",detail:"Business automation skill pack. See the full product page for included workflows.",url:"https://buy.stripe.com/00wfZiffR7r98UR5lRfnO03",icon:"⋈"},
{id:"suture",name:"Suture",group:"work",category:"Code quality & DevOps",price:19,description:"14 skills for code quality and development operations.",detail:"Code quality and DevOps skill pack. Review the included skills and your setup before purchasing.",url:"https://buy.stripe.com/bJeaEY5Fh9zh4EB01xfnO05",icon:"⟡"},
{id:"visage",name:"Visage",group:"work",category:"Frontend & design",price:19,description:"12 skills for interfaces and frontend design.",detail:"Frontend and design skill pack. See the full description for each included skill.",url:"https://buy.stripe.com/00wbJ2d7J4eXb2ZbKffnO07",icon:"▱"},
{id:"scry",name:"Scry",group:"work",category:"Data & analytics",price:19,description:"12 skills for working with data.",detail:"Data and analytics skill pack. Explore the included skills on the current product page.",url:"https://buy.stripe.com/00w9AU1p15j18UR9C7fnO08",icon:"◎"},
{id:"siphon",name:"Siphon",group:"work",category:"Growth & conversion",price:24,description:"15 skills for marketing and conversion workflows.",detail:"Growth and conversion skill pack. See the full list to decide whether it fits your work.",url:"https://buy.stripe.com/14AeVeaZB5j1efb4hNfnO09",icon:"⤴"},
{id:"bundle",name:"The full skill-pack bundle",group:"work",category:"All 10 skill packs",price:149,description:"The complete collection of ten skill packs.",detail:"Includes Siren, Reaper, Horde, Wraith, Suture, Animus, Visage, Scry, Siphon, and Thrall. Desktop apps and icon sets are separate offerings.",url:"https://buy.stripe.com/3cIfZi9VxaDl1spbKffnO0b",icon:"✧"},
{id:"warden-free",name:"Workspace Warden · Free",group:"ai",category:"Windows app / free download",price:0,description:"Try the chat workspace with your own AI provider.",detail:"Free Windows download. You supply your provider. Provider usage charges, if any, are separate.",url:"https://www.revenantsystems.net/downloads/RevenantWorkspaceWarden-1.0.0-win-x64.zip",icon:"◉"},
{id:"warden",name:"Workspace Warden",group:"ai",category:"Windows app / paid unlock",price:29,description:"Unlock the tutor, quiz, and security scanner tools.",detail:"Paid Workspace Warden unlock. Download the free app first and review the feature list on the current product page.",url:"https://buy.stripe.com/7sYeVec3FfXFdb76pVfnO0e",icon:"◉"},
{id:"rts-free",name:"Theme Studio · Free",group:"desktop",category:"Windows app / free download",price:0,description:"Try Revenant Theme Studio for Windows.",detail:"Free Theme Studio download. Explore Windows customization before choosing the Pro unlock.",url:"https://www.revenantsystems.net/downloads/RevenantThemeStudio-1.0.0.zip",icon:"▧"},
{id:"rts",name:"Theme Studio Pro",group:"desktop",category:"Windows app / paid unlock",price:10,description:"Unlock the Pro features in Theme Studio.",detail:"Pro unlock for Revenant Theme Studio. The current product page explains its features and the free tier.",url:"https://buy.stripe.com/3cIfZigjVh1J9YV8y3fnO00",icon:"▧"},
{id:"jade-icons",name:"Jade-Gold icons",group:"desktop",category:"Premium icon set",price:5,description:"Emerald and gold for your Windows workspace.",detail:"Jade-Gold premium icon set. View the full preview on the current product page.",url:"https://buy.stripe.com/8x24gAaZB9zh7QN6pVfnO0c",icon:"▦"},
{id:"suede-icons",name:"Black-Suede & Gold icons",group:"desktop",category:"Premium icon set",price:5,description:"A dark, textured icon set with gold accents.",detail:"Black-Suede and Gold premium icon set. View the full preview on the current product page.",url:"https://buy.stripe.com/aFa3cw5Fhh1Jefb8y3fnO0d",icon:"▦"}
];